name: game_cars
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: http://ondart.me/
version: 0.0.1
description: >
  A canvas game with moving rectangles of different sizes and colors, whose objective is to move out the red rectangle without collisions.
dependencies:
  simple_audio:
    git: https://github.com/johnmccutchan/simpleaudio.git